from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_Debugger(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")

        self.CamAll = QtWidgets.QGroupBox(self.centralWidget)
        self.CamAll.setGeometry(QtCore.QRect(10, 10, 971, 51))
        self.CamAll.setObjectName("CamAll")
        self.gridLayoutWidget = QtWidgets.QWidget(self.CamAll)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 971, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayoutAllButtons = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayoutAllButtons.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutAllButtons.setSpacing(6)
        self.gridLayoutAllButtons.setObjectName("gridLayoutAllButtons")
        self.AllStartRecording = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.AllStartRecording.setObjectName("AllStartRecording")
        self.gridLayoutAllButtons.addWidget(self.AllStartRecording, 0, 0)
        self.AllStopRecording = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.AllStopRecording.setEnabled(False)
        self.AllStopRecording.setObjectName("AllStopRecording")
        self.gridLayoutAllButtons.addWidget(self.AllStopRecording, 0, 1)

        self.Cam0 = QtWidgets.QGroupBox(self.centralWidget)
        self.Cam0.setGeometry(QtCore.QRect(10, 70, 481, 331))
        self.Cam0.setObjectName("Cam0")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.Cam0)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 481, 281))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayoutCam0Panel = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayoutCam0Panel.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutCam0Panel.setSpacing(6)
        self.gridLayoutCam0Panel.setObjectName("gridLayoutCam0Panel")
        self.Cam0Panel = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.Cam0Panel.setObjectName("cam0")
        self.gridLayoutCam0Panel.addWidget(self.Cam0Panel, 0, 0)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.Cam0)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 300, 481, 31))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayoutCam0Buttons = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayoutCam0Buttons.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutCam0Buttons.setSpacing(6)
        self.gridLayoutCam0Buttons.setObjectName("gridLayoutCam0Buttons")
        self.Cam0StartRecording = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.Cam0StartRecording.setObjectName("Cam0StartRecording")
        self.gridLayoutCam0Buttons.addWidget(self.Cam0StartRecording, 0, 0)
        self.Cam0StopRecording = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.Cam0StopRecording.setEnabled(False)
        self.Cam0StopRecording.setObjectName("Cam0StopRecording")
        self.gridLayoutCam0Buttons.addWidget(self.Cam0StopRecording, 0, 1)

        self.Cam1 = QtWidgets.QGroupBox(self.centralWidget)
        self.Cam1.setGeometry(QtCore.QRect(500, 70, 481, 331))
        self.Cam1.setObjectName("Cam1")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.Cam1)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 481, 281))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayoutCam1Panel = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayoutCam1Panel.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutCam1Panel.setSpacing(6)
        self.gridLayoutCam1Panel.setObjectName("gridLayoutCam1Panel")
        self.Cam1Panel = QtWidgets.QWidget(self.gridLayoutWidget_3)
        self.Cam1Panel.setObjectName("Cam1Panel")
        self.gridLayoutCam1Panel.addWidget(self.Cam1Panel, 0, 0)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.Cam1)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(0, 300, 481, 31))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayoutCam1Buttons = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayoutCam1Buttons.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutCam1Buttons.setSpacing(6)
        self.gridLayoutCam1Buttons.setObjectName("gridLayoutCam1Buttons")
        self.Cam1StartRecording = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.Cam1StartRecording.setObjectName("Cam1StartRecording")
        self.gridLayoutCam1Buttons.addWidget(self.Cam1StartRecording, 0, 0)
        self.Cam1StopRecording = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.Cam1StopRecording.setEnabled(False)
        self.Cam1StopRecording.setObjectName("Cam1StopRecording")
        self.gridLayoutCam1Buttons.addWidget(self.Cam1StopRecording, 0, 1)

        self.Cam2 = QtWidgets.QGroupBox(self.centralWidget)
        self.Cam2.setGeometry(QtCore.QRect(10, 410, 481, 331))
        self.Cam2.setObjectName("Cam2")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.Cam2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 20, 481, 281))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayoutCam2Panel = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayoutCam2Panel.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutCam2Panel.setSpacing(6)
        self.gridLayoutCam2Panel.setObjectName("gridLayoutCam2Panel")
        self.Cam2Panel = QtWidgets.QWidget(self.gridLayoutWidget_4)
        self.Cam2Panel.setObjectName("Cam2Panel")
        self.gridLayoutCam2Panel.addWidget(self.Cam2Panel, 0, 0)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.Cam2)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(0, 300, 481, 31))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayoutCam2Buttons = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayoutCam2Buttons.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutCam2Buttons.setSpacing(6)
        self.gridLayoutCam2Buttons.setObjectName("gridLayoutCam2Buttons")
        self.Cam2StartRecording = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        self.Cam2StartRecording.setObjectName("Cam2StartRecording")
        self.gridLayoutCam2Buttons.addWidget(self.Cam2StartRecording, 0, 0)
        self.Cam2StopRecording = QtWidgets.QPushButton(self.gridLayoutWidget_8)
        self.Cam2StopRecording.setEnabled(False)
        self.Cam2StopRecording.setObjectName("Cam2StopRecording")
        self.gridLayoutCam2Buttons.addWidget(self.Cam2StopRecording, 0, 1)

        self.Cam3 = QtWidgets.QGroupBox(self.centralWidget)
        self.Cam3.setGeometry(QtCore.QRect(500, 410, 481, 331))
        self.Cam3.setObjectName("Cam3")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.Cam3)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 20, 481, 281))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayoutCam3Panel = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayoutCam3Panel.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutCam3Panel.setSpacing(6)
        self.gridLayoutCam3Panel.setObjectName("gridLayoutCam3Panel")
        self.Cam3Panel = QtWidgets.QWidget(self.gridLayoutWidget_5)
        self.Cam3Panel.setObjectName("Cam3Panel")
        self.gridLayoutCam3Panel.addWidget(self.Cam3Panel, 0, 0)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.Cam3)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(0, 300, 481, 31))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayoutCam3Buttons = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayoutCam3Buttons.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutCam3Buttons.setSpacing(6)
        self.gridLayoutCam3Buttons.setObjectName("gridLayoutCam3Buttons")
        self.Cam3StartRecording = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        self.Cam3StartRecording.setObjectName("Cam3StartRecording")
        self.gridLayoutCam3Buttons.addWidget(self.Cam3StartRecording, 0, 0)
        self.Cam3StopRecording = QtWidgets.QPushButton(self.gridLayoutWidget_9)
        self.Cam3StopRecording.setEnabled(False)
        self.Cam3StopRecording.setObjectName("Cam3StopRecording")
        self.gridLayoutCam3Buttons.addWidget(self.Cam3StopRecording, 0, 1)

        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CamAll.setTitle(_translate("MainWindow", "CamAll"))
        self.AllStartRecording.setText(_translate("MainWindow", "Start Recording"))
        self.AllStopRecording.setText(_translate("MainWindow", "Stop Recording"))
        self.Cam0.setTitle(_translate("MainWindow", "Cam0"))
        self.Cam0StartRecording.setText(_translate("MainWindow", "Start Recording"))
        self.Cam0StopRecording.setText(_translate("MainWindow", "Stop Recording"))
        self.Cam1.setTitle(_translate("MainWindow", "Cam1"))
        self.Cam1StartRecording.setText(_translate("MainWindow", "Start Recording"))
        self.Cam1StopRecording.setText(_translate("MainWindow", "Stop Recording"))
        self.Cam2.setTitle(_translate("MainWindow", "Cam2"))
        self.Cam2StartRecording.setText(_translate("MainWindow", "Start Recording"))
        self.Cam2StopRecording.setText(_translate("MainWindow", "Stop Recording"))
        self.Cam3.setTitle(_translate("MainWindow", "Cam3"))
        self.Cam3StartRecording.setText(_translate("MainWindow", "Start Recording"))
        self.Cam3StopRecording.setText(_translate("MainWindow", "Stop Recording"))